package Reservation;

public enum ReservationResult {

    FAILEDNOTENOUGHFUNDS,
    FAILEDCAPACITY,
    FAILEDWRONGROOMTYPE,
    FAILEDALREADYRESERVED,
    FAILEDENDDATEISBEFORESTARTDATE,
    SUCCESS;

}
